spring:
  main:
    banner-mode: off
    web-application-type: none
  application:
    name: mcp-server-personal
  ai:
    mcp:
      server:
        stdio: true
        name: mcp-server-personal
        version: 1.0.0
        instructions: A personal MCP server for handling AI agent requests. Various tools will be exposed

logging:
  level:
    root: OFF